number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]№_`{|}~ €₽"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ'
experiment_name: 'ru_filtered'
train_data: '/home/ivan/NapoleonIT/OCR/data/train'
valid_data: '/home/ivan/NapoleonIT/OCR/data/val'
manualSeed: 1111
workers: 6
batch_size: 64  
num_iter: 30000 
valInterval: 200
saved_model: '/home/ivan/NapoleonIT/OCR/easyocr/saved_models/cyrillic_g2.pth'
FT: True
optim: False
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
select_data: 'train'
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 68 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False 