Global:
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./svtr
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: null
  character_type: en
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./svtr/predicts_svtr_large.txt
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 8.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.000125
    warmup_epoch: 2
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize:
    - 32
    - 64
    tps_outputsize:
    - 48
    - 160
    num_control_points: 20
    tps_margins:
    - 0.05
    - 0.05
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size:
    - 48
    - 160
    out_char_num: 40
    out_channels: 384
    patch_merging: Conv
    embed_dim:
    - 192
    - 256
    - 512
    depth:
    - 3
    - 9
    - 9
    num_heads:
    - 6
    - 8
    - 16
    mixer:
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
Loss:
  name: CTCLoss
PostProcess:
  name: SVTRLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../data/train_limited_50
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        character_dict_path: null
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../home/research/NapoleonPractice/data/val
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - SVTRRecResizeImg:
        character_dict_path: null
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 2
profiler_options: null
