path_to_model_dir : "/data/models/microsofttrocr-large-printed/model_default"
path_to_processor_dir : "/data/models/microsofttrocr-large-printed/processor_default"
path_to_test_dataset : "/data/data/test"
path_to_train_dataset : "/data/data/train_limited_50"
path_to_val_dataset : "/data/data/val"
train_metadata_file_name : "annotations_train_limited_50.txt"
val_metadata_file_name : "annotations_val.txt"
output_dir: "/dataresults/microsofttrocr-large-printed"
device: "cuda"
optimizer: "AdamW"
optimizer_step : 5e-5
epoch : 50
batch_size : 64
task_name : "train_trocr_printed"
