# Datasets
train_dataset_id : "be957f87b2e94224b2559244d91cbbb7"
val_dataset_id : "c624941404fc4c8283e507ec86134e8e"
# Model 
task_id : "a3e2c78101934f5f8cf2d618b1f4c02f"
model_artifact : "model"
processor_artifact : "processor"
# Artifacts name
agent_model_dir : "./model"
agent_processor_dir: "./processor"
agent_train_dataset : "./dataset/train"
agent_val_dataset : "./dataset/val"
#Other info
train_metadata_file_name : "annotations_train_limited_50.txt"
val_metadata_file_name : "annotations_val.txt"
output_dir: "./results/microsofttrocr-large-printed"
device: "cuda"
optimizer: "AdamW"
optimizer_step : 5e-5
epoch : 20
batch_size : 64
task_name : "train_trocr_base_printed"
queue_name : "pavlov_0"
