number: '0123456789'
symbol: "None"
lang_char: "None"
experiment_name: 'custom_30000_iters_Adadelta'
train_data: '../data/train_limited_50'
valid_data: '../data/val'
task_name : 'custom_30000_iters_Adadelta'
train_metadata_file_name : "annotations_train_limited_50.txt"
val_metadata_file_name : "annotations_val.txt"
manualSeed: 1111
workers: 6
batch_size: 32
num_iter: 30000
valInterval: 200
saved_model: ''
FT: True
optim: "Adadelta"
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
select_data: 'images'
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 256
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False 
amp: False 